server:
  port: 8080

spring:
  application:
    name: zxf-springboot-trace-webflux

# 日志配置
logging:
  level:
    root: INFO
    zxf.trace: DEBUG  # 设置项目包的日志级别为DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG  # WebClient日志

# 跟踪配置
trace:
  sensitive-fields: password,token,credit_card,ssn,secret,key,authorization,auth  # 敏感字段列表
  mask-value: "******"  # 掩码字符
